version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: nest-mysql
    restart: always
    env_file:
      - .env.development
    ports:
      - '${MYSQL_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集
    volumes:
      - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    networks:
      - nest_net

  redis:
    image: redis:alpine
    container_name: nest-admin-redis
    restart: always
    env_file:
      - .env.development
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - nest_net

networks:
  nest_net:
    name: nest_net
